sudo: required
language: java
jdk:
  - oraclejdk8
script:
  mvn test
env:
- secure: "GnQeVwyXCTKAhnh7aKiIDVIkB5MII/VDBc7/bOaFn0B2YnG3ZBfTY4oKK8uQ/rbM1F4Epz9vXzV1Wo+jM66kLnj5d2loFIg3Yd38jfwSFVF1fXVi03Bc0i3j0/vy9fuqY3vguwTh6yAUNNgW1Ms4hRuWKh6pVXrNKBxYSct+UDLzSNrMOeze5CZUtiTmxtMX2JBVrGDF7fMLCYJbUB2waK5X0yDlpfAhxAvW6E6bVK1qqPuAbTSN3W63cRH0KfXdEdARUyByYfi1iJuDyNyDXatXd3cXG8WLJfU0B1+Dya84EJLXdb2dEDHqo3SOpMMYb/ZEMwwDlKP9NbMvlGPL38wUGKP7qL+N3ARuemLGXxLz5ymgn6x38vmn2YcjdNVcRexrtB4VMwYjcIOYA/3lZw70dAuVvo71nBf7AfBV9sO5n6JVvWpvN1dTEVjGMigX+KnLpeUvnHsgu7aJfAF1XbDe+0VB7meURNSRt3k93gieVA/fhEy10ygi0LwBX5+UCQOW9+5Rue/cHbpteRRLGVSfWrGAGM58llSFU1/dmrYy+9DlmpCa821Y5kfdEHqSFtxRRW1CEkfg7ce3I4rAqNXA0V08UJOumtmQ1Fch2gzx5jhj84MjZBC0z2cx3uc6/1EqM2MohEN5Pus/UEKd5rNBad3ssWnXHas1XykNSmM="

after_success:
- ./javadocs-to-gh-pages.sh
