sudo: required
language: java
jdk:
  - oraclejdk8
script:
  mvn test
env:
- secure: "oab3aAanWsh3fP5qrYeEJM3YKPkwnaTzz9bM2kJAkj++IpvHMaO9c/uglP6FT7ARz3BvgQwuSgh4bM7HBHccMIuYWnxwPvtIJm1owHcGTnqV9EvbXGuGFh+WJQCkhMPsmZLhgGYjYZCXEMST0/sC4SOsctA8kHPsbH1A9DHLEFXkhqxUW9E7nLqWKg//X89p5+GdJh/nVhC84T6rgiwNpa2TKVpf+eLS410NxqB7HnUw+IRqBi7Zg06uYTbwz8zD5D57qP9FW1uImnDx3YljtmNbzZqeoolvVjTdkV8j9Oe3SkPKIEPNd3Wf4/ycUppdmN0Z91i+trsLPbMVYTGCbbOeAYE6UpDZrA03AasNXtsgebvx56+V6pGJpx/hSYtTtxFEvXp+oFbj1qGvxmYHfexEiivDY1Uy3ur108KQNCDX/ghXvU2eqE+3qgsGNc3AIuDCli1kofNkkui4SCOYL/EtAAE4r4ENeM0i9CgDOiDyXFQ/t+miARG+DUaA9HdsNnvTjoR9DjDn/iKVRygJWfGBs2hgqlt4gkQf+HwtP9OX5fA8jFnIUsOYFW2giTXz5cpRYHJfAXjK96NZtGg71bIMlHIO+Urdr9vNlucPDI6FG7jODhomo45dHj38v1mL82ub0HqkgppNhNqfU/ry4FoWr4tvaqh92UMQw/reXQo="

after_success:
- ./javadocs-to-gh-pages.sh
