sudo: required
language: java
jdk:
  - oraclejdk8
script:
  mvn test
env:
  global:
  - secure: "Arioi7tjQOtSeC6oLEtyCPNrikI/1kKVzrFuPHuiEGhNo2Imq4VjOsohYkJM6dt2iSv9GVwsJp8B2rdOz7EQ+uWhUYlEJAwyq4PI1ADqo6x4iSoEd5UH0BCEGypO09VsKolFy7jsgxr0zANpoCuqc1hRmkJDu8UON8F0x8CsQBddilrDSHf5pHYNg8+/9swyPVD1DmtIOk4WrHBGm6WEWJO+hmtXRakaMwdLXlTnFseCPZigHczmRV05Ze5YSfQwSvw5QBaqJlaXNah6jONqUbLaDCimozOM1L6spAAH1aFutj1eai15YXQlAyh6628lsNBJYWB4Stgsty4hNz7G+Z106wNjLw+AgqrxCLrIiK1fmE97cNdoqn8pvVV9kJfh79WiSY+dVtVDTueQDDVqQG/eLySx79NVCi9EPREe1zi7vRE2MEbvoIXXaNeCTZYPJId98CZSgCQEurW26ee1VSQnfFBML8n7IwMb0WsvKdlTDZHuM7ozS5lTV3g1z5aekAHSCogi4zOjMpih4zgkLTsQdUCn9gSTn+XI1/vUjYfYZzl6woccHGrLbH4/qzRHpHFL2bBCNt0a5N1PvHEYcSciMJ7E0/BTZEgm/MR1i0xdyt58FhznDy3EJkTgOumazdieXhOfW0Bj2AdzcJvhoI34CrvGBzn0G5pDFO1bCsU="
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- ./javadocs-to-gh-pages.sh
